# Generated by Django 3.0.1 on 2020-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200201_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_Of_birth',
            field=models.DateField(),
        ),
    ]
