# Generated by Django 3.0.1 on 2020-02-01 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200201_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_mobile',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
