# Generated by Django 2.2.9 on 2020-02-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20200201_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert'), ('S', 'Sensing'), ('N', 'intutive'), ('T', 'Thinkimg'), ('F', 'Feeling'), ('J', 'Judging'), ('P', 'perceivimg')], default='I', max_length=1)),
                ('question2', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert'), ('S', 'Sensing'), ('N', 'intutive'), ('T', 'Thinkimg'), ('F', 'Feeling'), ('J', 'Judging'), ('P', 'perceivimg')], default='S', max_length=1)),
                ('question3', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert'), ('S', 'Sensing'), ('N', 'intutive'), ('T', 'Thinkimg'), ('F', 'Feeling'), ('J', 'Judging'), ('P', 'perceivimg')], default='T', max_length=1)),
                ('question4', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert'), ('S', 'Sensing'), ('N', 'intutive'), ('T', 'Thinkimg'), ('F', 'Feeling'), ('J', 'Judging'), ('P', 'perceivimg')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
