# Generated by Django 2.2.9 on 2020-03-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20200201_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='username')),
                ('question1', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert')], default='I', max_length=1)),
                ('question2', models.CharField(choices=[('S', 'Sensing'), ('N', 'Intutive')], default='S', max_length=1)),
                ('question3', models.CharField(choices=[('T', 'Thinking'), ('F', 'Feeling')], default='T', max_length=1)),
                ('question4', models.CharField(choices=[('J', 'Judging'), ('P', 'Perceiving')], default='J', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
