# Generated by Django 2.2.9 on 2020-02-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200225_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
