# Generated by Django 3.0.1 on 2020-02-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='codes',
            new_name='Code',
        ),
    ]
