# Generated by Django 3.0.1 on 2020-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_combinedcodetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedCodeTable',
        ),
    ]
