# Generated by Django 3.0.1 on 2020-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_combinedcodetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedCodeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinedcode', models.CharField(max_length=255)),
                ('combinedcode_means', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
