# Generated by Django 3.0.1 on 2020-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_combinedcodetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedcodetable',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
