# Generated by Django 3.0.1 on 2020-02-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200202_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodAndStess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angry', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('happy', models.FloatField()),
                ('neutral', models.FloatField()),
                ('sad', models.FloatField()),
                ('surprise', models.FloatField()),
            ],
        ),
    ]
