# Generated by Django 3.0.1 on 2020-02-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_moodandstess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodAndStess',
        ),
    ]
