# Generated by Django 3.0.1 on 2020-03-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200303_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodstress',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
