# Generated by Django 3.0.1 on 2020-03-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_moodstress_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodStress',
        ),
    ]
