# Generated by Django 3.0.1 on 2020-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_moodstress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodStress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('angry', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('happy', models.FloatField()),
                ('neutral', models.FloatField()),
                ('sad', models.FloatField()),
                ('surprise', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'created')},
            },
        ),
    ]
