# Generated by Django 3.0.4 on 2020-03-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_moodstress'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodstress',
            name='user',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='moodstress',
            unique_together={('user_id', 'created')},
        ),
        migrations.CreateModel(
            name='HowsDay',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('feeling', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'created')},
            },
        ),
    ]
